-- ratings_table.sql

CREATE TABLE ratings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), -- or INT AUTO_INCREMENT for MySQL
    storeId UUID NOT NULL,
    userId UUID NOT NULL,
    ratingValue INT NOT NULL CHECK (ratingValue BETWEEN 1 AND 5),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_store FOREIGN KEY (storeId) REFERENCES stores(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
