-- stores_table.sql

CREATE TABLE stores (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), -- or INT AUTO_INCREMENT for MySQL
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE CHECK (
        email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
    ),
    address VARCHAR(400) NOT NULL CHECK (CHAR_LENGTH(address) <= 400),
    ownerId UUID NOT NULL UNIQUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_owner FOREIGN KEY (ownerId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
